from __future__ import annotations

from pathlib import Path


BOOTSTRAP_DIR = Path("checkpoints/bootstrap")


def _ckpt(name: str) -> str:
    return str((BOOTSTRAP_DIR / name).as_posix())


PRESET_ARGS: dict[str, list[str]] = {
    "old_anchor_exact": [
        "--run-name",
        "modal_geovit_teacher_init_10k2k_e20_repro",
        "--epochs",
        "20",
        "--limit-train",
        "10000",
        "--limit-test",
        "2000",
        "--batch-size",
        "64",
        "--eval-batch-size",
        "128",
        "--num-workers",
        "4",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--teacher-checkpoint",
        _ckpt("modal_plain_teacher_10k2k_e20_best.pth"),
        "--teacher-init-student",
        "--teacher-logit-weight",
        "0.0",
        "--teacher-feature-weight",
        "0.0",
        "--anchor-logit-weight",
        "0.0",
        "--anchor-feature-weight",
        "0.0",
        "--anchor-block-feature-weight",
        "0.0",
        "--mixup-alpha",
        "0.2",
        "--cutmix-alpha",
        "1.0",
        "--mix-prob",
        "1.0",
        "--label-smoothing",
        "0.1",
        "--ema-decay",
        "0.9998",
        "--ema-start-epoch",
        "5",
    ],
    "old_anchor_continue": [
        "--run-name",
        "modal_geovit_teacher_init_resume_oldbest_e8",
        "--epochs",
        "8",
        "--limit-train",
        "10000",
        "--limit-test",
        "2000",
        "--batch-size",
        "64",
        "--eval-batch-size",
        "128",
        "--num-workers",
        "4",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--teacher-checkpoint",
        _ckpt("modal_plain_teacher_10k2k_e20_best.pth"),
        "--teacher-init-student",
        "--student-checkpoint",
        _ckpt("old_modal_geovit_teacher_init_10k2k_e20_best.pth"),
        "--teacher-logit-weight",
        "0.0",
        "--teacher-feature-weight",
        "0.0",
        "--anchor-logit-weight",
        "0.0",
        "--anchor-feature-weight",
        "0.0",
        "--anchor-block-feature-weight",
        "0.0",
        "--mixup-alpha",
        "0.2",
        "--cutmix-alpha",
        "1.0",
        "--mix-prob",
        "1.0",
        "--label-smoothing",
        "0.1",
        "--ema-decay",
        "0.9998",
        "--ema-start-epoch",
        "1",
        "--lr",
        "7.5e-5",
        "--warmup-epochs",
        "1",
    ],
    "smat_continue_oldwinner": [
        "--run-name",
        "modal_geovit_smat_continue_oldwinner_e8",
        "--epochs",
        "8",
        "--limit-train",
        "10000",
        "--limit-test",
        "2000",
        "--batch-size",
        "64",
        "--eval-batch-size",
        "128",
        "--num-workers",
        "4",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--teacher-checkpoint",
        _ckpt("modal_plain_teacher_10k2k_e20_best.pth"),
        "--anchor-checkpoint",
        _ckpt("old_modal_geovit_teacher_init_10k2k_e20_best.pth"),
        "--student-checkpoint",
        _ckpt("old_modal_geovit_anchorrefine_warm075_head_anchorfeat_kd_10k2k_e10_best.pth"),
        "--teacher-init-student",
        "--manifold-refine-only",
        "--manifold-train-head",
        "--semantic-manifold-mode",
        "--strict-semantic-operator",
        "--flow-rank",
        "8",
        "--warm-start-semantic-from-anchor",
        "--warm-start-flow-scale",
        "0.75",
        "--teacher-logit-weight",
        "0.1",
        "--teacher-feature-weight",
        "0.1",
        "--anchor-logit-weight",
        "0.0",
        "--anchor-feature-weight",
        "0.05",
        "--semantic-anchor-weight",
        "0.05",
        "--semantic-expert-weight",
        "0.01",
        "--semantic-mode-weight",
        "0.02",
        "--lr",
        "7.5e-5",
        "--warmup-epochs",
        "1",
        "--ema-decay",
        "0.9998",
        "--ema-start-epoch",
        "1",
    ],
    "smat_continue_oldwinner_blockfeat": [
        "--run-name",
        "modal_geovit_smat_continue_oldwinner_blockfeat_e8",
        "--epochs",
        "8",
        "--limit-train",
        "10000",
        "--limit-test",
        "2000",
        "--batch-size",
        "64",
        "--eval-batch-size",
        "128",
        "--num-workers",
        "8",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--teacher-checkpoint",
        _ckpt("modal_plain_teacher_10k2k_e20_best.pth"),
        "--anchor-checkpoint",
        _ckpt("old_modal_geovit_teacher_init_10k2k_e20_best.pth"),
        "--student-checkpoint",
        _ckpt("old_modal_geovit_anchorrefine_warm075_head_anchorfeat_kd_10k2k_e10_best.pth"),
        "--teacher-init-student",
        "--manifold-refine-only",
        "--manifold-train-head",
        "--semantic-manifold-mode",
        "--strict-semantic-operator",
        "--flow-rank",
        "8",
        "--warm-start-semantic-from-anchor",
        "--warm-start-flow-scale",
        "0.75",
        "--teacher-logit-weight",
        "0.1",
        "--teacher-feature-weight",
        "0.1",
        "--anchor-logit-weight",
        "0.0",
        "--anchor-feature-weight",
        "0.05",
        "--anchor-block-feature-weight",
        "0.05",
        "--anchor-block-feature-layers",
        "3",
        "--semantic-anchor-weight",
        "0.05",
        "--semantic-expert-weight",
        "0.01",
        "--semantic-mode-weight",
        "0.02",
        "--lr",
        "7.5e-5",
        "--warmup-epochs",
        "1",
        "--ema-decay",
        "0.9998",
        "--ema-start-epoch",
        "1",
    ],
    "smat_continue_oldwinner_blockfeat_bf16": [
        "--run-name",
        "modal_geovit_smat_continue_oldwinner_blockfeat_bf16_e8",
        "--epochs",
        "8",
        "--limit-train",
        "10000",
        "--limit-test",
        "2000",
        "--batch-size",
        "64",
        "--eval-batch-size",
        "128",
        "--num-workers",
        "8",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--teacher-checkpoint",
        _ckpt("modal_plain_teacher_10k2k_e20_best.pth"),
        "--anchor-checkpoint",
        _ckpt("old_modal_geovit_teacher_init_10k2k_e20_best.pth"),
        "--student-checkpoint",
        _ckpt("old_modal_geovit_anchorrefine_warm075_head_anchorfeat_kd_10k2k_e10_best.pth"),
        "--teacher-init-student",
        "--manifold-refine-only",
        "--manifold-train-head",
        "--semantic-manifold-mode",
        "--strict-semantic-operator",
        "--flow-rank",
        "8",
        "--warm-start-semantic-from-anchor",
        "--warm-start-flow-scale",
        "0.75",
        "--teacher-logit-weight",
        "0.1",
        "--teacher-feature-weight",
        "0.1",
        "--anchor-logit-weight",
        "0.0",
        "--anchor-feature-weight",
        "0.05",
        "--anchor-block-feature-weight",
        "0.05",
        "--anchor-block-feature-layers",
        "3",
        "--semantic-anchor-weight",
        "0.05",
        "--semantic-expert-weight",
        "0.01",
        "--semantic-mode-weight",
        "0.02",
        "--lr",
        "7.5e-5",
        "--warmup-epochs",
        "1",
        "--ema-decay",
        "0.9998",
        "--ema-start-epoch",
        "1",
        "--amp-dtype",
        "bfloat16",
    ],
    "align_continue_oldwinner_blockfeat": [
        "--run-name",
        "modal_geovit_align_continue_oldwinner_blockfeat_e8",
        "--epochs",
        "8",
        "--limit-train",
        "10000",
        "--limit-test",
        "2000",
        "--batch-size",
        "64",
        "--eval-batch-size",
        "128",
        "--num-workers",
        "8",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--teacher-checkpoint",
        _ckpt("modal_plain_teacher_10k2k_e20_best.pth"),
        "--anchor-checkpoint",
        _ckpt("old_modal_geovit_teacher_init_10k2k_e20_best.pth"),
        "--student-checkpoint",
        _ckpt("old_modal_geovit_anchorrefine_warm075_head_anchorfeat_kd_10k2k_e10_best.pth"),
        "--teacher-init-student",
        "--manifold-refine-only",
        "--manifold-train-head",
        "--manifold-train-output-basis",
        "--manifold-alignment-mode",
        "--flow-rank",
        "8",
        "--teacher-logit-weight",
        "0.1",
        "--teacher-feature-weight",
        "0.1",
        "--anchor-logit-weight",
        "0.0",
        "--anchor-feature-weight",
        "0.05",
        "--anchor-block-feature-weight",
        "0.05",
        "--anchor-block-feature-layers",
        "3",
        "--flow-anchor-weight",
        "0.01",
        "--flow-energy-weight",
        "0.001",
        "--lr",
        "7.5e-5",
        "--warmup-epochs",
        "1",
        "--ema-decay",
        "0.9998",
        "--ema-start-epoch",
        "1",
    ],
    "align_continue_oldwinner_blockfeat_bf16": [
        "--run-name",
        "modal_geovit_align_continue_oldwinner_blockfeat_bf16_e8",
        "--epochs",
        "8",
        "--limit-train",
        "10000",
        "--limit-test",
        "2000",
        "--batch-size",
        "64",
        "--eval-batch-size",
        "128",
        "--num-workers",
        "8",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--teacher-checkpoint",
        _ckpt("modal_plain_teacher_10k2k_e20_best.pth"),
        "--anchor-checkpoint",
        _ckpt("old_modal_geovit_teacher_init_10k2k_e20_best.pth"),
        "--student-checkpoint",
        _ckpt("old_modal_geovit_anchorrefine_warm075_head_anchorfeat_kd_10k2k_e10_best.pth"),
        "--teacher-init-student",
        "--manifold-refine-only",
        "--manifold-train-head",
        "--manifold-train-output-basis",
        "--manifold-alignment-mode",
        "--flow-rank",
        "8",
        "--teacher-logit-weight",
        "0.1",
        "--teacher-feature-weight",
        "0.1",
        "--anchor-logit-weight",
        "0.0",
        "--anchor-feature-weight",
        "0.05",
        "--anchor-block-feature-weight",
        "0.05",
        "--anchor-block-feature-layers",
        "3",
        "--flow-anchor-weight",
        "0.01",
        "--flow-energy-weight",
        "0.001",
        "--lr",
        "7.5e-5",
        "--warmup-epochs",
        "1",
        "--ema-decay",
        "0.9998",
        "--ema-start-epoch",
        "1",
        "--amp-dtype",
        "bfloat16",
    ],
    "oldwinner_continue_clip": [
        "--run-name",
        "modal_geovit_oldwinner_continue_clip_e10",
        "--epochs",
        "10",
        "--limit-train",
        "10000",
        "--limit-test",
        "2000",
        "--batch-size",
        "64",
        "--eval-batch-size",
        "128",
        "--num-workers",
        "8",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--teacher-checkpoint",
        _ckpt("modal_plain_teacher_10k2k_e20_best.pth"),
        "--anchor-checkpoint",
        _ckpt("old_modal_geovit_teacher_init_10k2k_e20_best.pth"),
        "--student-checkpoint",
        _ckpt("old_modal_geovit_anchorrefine_warm075_head_anchorfeat_kd_10k2k_e10_best.pth"),
        "--teacher-init-student",
        "--manifold-refine-only",
        "--manifold-train-head",
        "--manifold-train-output-basis",
        "--flow-rank",
        "8",
        "--teacher-logit-weight",
        "0.1",
        "--teacher-feature-weight",
        "0.1",
        "--anchor-logit-weight",
        "0.0",
        "--anchor-feature-weight",
        "0.05",
        "--lr",
        "5e-5",
        "--warmup-epochs",
        "1",
        "--ema-decay",
        "0.9998",
        "--ema-start-epoch",
        "1",
        "--grad-clip-norm",
        "1.0",
    ],
    "oldwinner_continue_clip_flowreg": [
        "--run-name",
        "modal_geovit_oldwinner_continue_clip_flowreg_e10",
        "--epochs",
        "10",
        "--limit-train",
        "10000",
        "--limit-test",
        "2000",
        "--batch-size",
        "64",
        "--eval-batch-size",
        "128",
        "--num-workers",
        "8",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--teacher-checkpoint",
        _ckpt("modal_plain_teacher_10k2k_e20_best.pth"),
        "--anchor-checkpoint",
        _ckpt("old_modal_geovit_teacher_init_10k2k_e20_best.pth"),
        "--student-checkpoint",
        _ckpt("old_modal_geovit_anchorrefine_warm075_head_anchorfeat_kd_10k2k_e10_best.pth"),
        "--teacher-init-student",
        "--manifold-refine-only",
        "--manifold-train-head",
        "--manifold-train-output-basis",
        "--flow-rank",
        "8",
        "--teacher-logit-weight",
        "0.1",
        "--teacher-feature-weight",
        "0.1",
        "--anchor-logit-weight",
        "0.0",
        "--anchor-feature-weight",
        "0.05",
        "--flow-anchor-weight",
        "0.005",
        "--flow-energy-weight",
        "0.0005",
        "--lr",
        "5e-5",
        "--warmup-epochs",
        "1",
        "--ema-decay",
        "0.9998",
        "--ema-start-epoch",
        "1",
        "--grad-clip-norm",
        "1.0",
    ],
    "smoke_geo_refine_winner": [
        "--run-name",
        "modal_smoke_georefine_from268_geoheadplushead_e6_seed3",
        "--epochs",
        "6",
        "--limit-train",
        "2000",
        "--limit-test",
        "500",
        "--batch-size",
        "128",
        "--eval-batch-size",
        "256",
        "--num-workers",
        "4",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--student-checkpoint",
        _ckpt("modal_smoke_oldwinner_headonly_probe_noaug_e10_seed3_best.pth"),
        "--geo-refine-only",
        "--geo-train-head",
        "--disable-strong-aug",
        "--mixup-alpha",
        "0",
        "--cutmix-alpha",
        "0",
        "--mix-prob",
        "0",
        "--label-smoothing",
        "0",
        "--ema-decay",
        "0",
        "--warmup-epochs",
        "0",
        "--min-lr-ratio",
        "0.1",
        "--lr",
        "5e-5",
        "--weight-decay",
        "0.01",
        "--grad-clip-norm",
        "0.5",
        "--eval-hflip-tta",
        "--eval-shift-tta",
        "1",
        "--seed",
        "3",
    ],
    "smoke_geo_refine_winner_basis": [
        "--run-name",
        "modal_smoke_georefine_from268_geoheadplusbasis_e6_seed3",
        "--epochs",
        "6",
        "--limit-train",
        "2000",
        "--limit-test",
        "500",
        "--batch-size",
        "128",
        "--eval-batch-size",
        "256",
        "--num-workers",
        "4",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--student-checkpoint",
        _ckpt("modal_smoke_oldwinner_headonly_probe_noaug_e10_seed3_best.pth"),
        "--geo-refine-only",
        "--geo-train-head",
        "--geo-train-output-basis",
        "--disable-strong-aug",
        "--mixup-alpha",
        "0",
        "--cutmix-alpha",
        "0",
        "--mix-prob",
        "0",
        "--label-smoothing",
        "0",
        "--ema-decay",
        "0",
        "--warmup-epochs",
        "0",
        "--min-lr-ratio",
        "0.1",
        "--lr",
        "3e-5",
        "--weight-decay",
        "0.01",
        "--grad-clip-norm",
        "0.5",
        "--eval-hflip-tta",
        "--eval-shift-tta",
        "1",
        "--seed",
        "3",
    ],
    "smoke_geo_curriculum_winner": [
        "--run-name",
        "modal_smoke_oldwinner_curriculum_headgeo_e16_seed3",
        "--epochs",
        "16",
        "--limit-train",
        "2000",
        "--limit-test",
        "500",
        "--batch-size",
        "128",
        "--eval-batch-size",
        "256",
        "--num-workers",
        "4",
        "--prefetch-factor",
        "4",
        "--eval-prefetch-factor",
        "2",
        "--student-checkpoint",
        _ckpt("old_modal_geovit_anchorrefine_warm075_head_anchorfeat_kd_10k2k_e10_best.pth"),
        "--geo-refine-only",
        "--geo-train-head",
        "--geo-head-warmup-epochs",
        "10",
        "--head-probe-lr",
        "3e-4",
        "--disable-strong-aug",
        "--mixup-alpha",
        "0",
        "--cutmix-alpha",
        "0",
        "--mix-prob",
        "0",
        "--label-smoothing",
        "0",
        "--ema-decay",
        "0",
        "--warmup-epochs",
        "0",
        "--min-lr-ratio",
        "0.1",
        "--lr",
        "5e-5",
        "--weight-decay",
        "0.01",
        "--grad-clip-norm",
        "0.5",
        "--eval-hflip-tta",
        "--eval-shift-tta",
        "1",
        "--seed",
        "3",
    ],
    "smoke_mid192_plain_e40": [
        "--run-name",
        "modal_smoke_plain_mid192d6_nomix_noema_e40",
        "--epochs",
        "40",
        "--limit-train",
        "2000",
        "--limit-test",
        "500",
        "--batch-size",
        "96",
        "--eval-batch-size",
        "192",
        "--embed-dim",
        "192",
        "--depth",
        "6",
        "--num-heads",
        "6",
        "--no-geo-on-fc1",
        "--disable-strong-aug",
        "--lr",
        "3e-4",
        "--weight-decay",
        "0.05",
        "--label-smoothing",
        "0.05",
        "--ema-decay",
        "0",
    ],
    "smoke_mid192_geo_winner": [
        "--run-name",
        "modal_smoke_geovit_mid192d6_rank114_spec085_noclip_wd008_e40",
        "--epochs",
        "40",
        "--limit-train",
        "2000",
        "--limit-test",
        "500",
        "--batch-size",
        "96",
        "--eval-batch-size",
        "192",
        "--embed-dim",
        "192",
        "--depth",
        "6",
        "--num-heads",
        "6",
        "--fc1-base-rank",
        "114",
        "--residual-scale",
        "0.85",
        "--spectral-scale",
        "0.85",
        "--low-rank-scale",
        "0.5",
        "--rotation-scale",
        "0.0",
        "--disable-local-geo",
        "--geo-start-epoch",
        "1",
        "--geo-ramp-epochs",
        "6",
        "--geo-target-scale",
        "0.65",
        "--geo-end-scale",
        "0.45",
        "--geo-decay-start-epoch",
        "20",
        "--geo-low-rank-end-mult",
        "0.6",
        "--geo-low-rank-decay-start-epoch",
        "22",
        "--disable-strong-aug",
        "--lr",
        "3e-4",
        "--weight-decay",
        "0.08",
        "--label-smoothing",
        "0.05",
        "--ema-decay",
        "0",
    ],
    "smoke_mid192_geo_clip05": [
        "--run-name",
        "modal_smoke_geovit_mid192d6_rank114_spec085_noclip_wd008_clip05_e40",
        "--epochs",
        "40",
        "--limit-train",
        "2000",
        "--limit-test",
        "500",
        "--batch-size",
        "96",
        "--eval-batch-size",
        "192",
        "--embed-dim",
        "192",
        "--depth",
        "6",
        "--num-heads",
        "6",
        "--fc1-base-rank",
        "114",
        "--residual-scale",
        "0.85",
        "--spectral-scale",
        "0.85",
        "--low-rank-scale",
        "0.5",
        "--rotation-scale",
        "0.0",
        "--disable-local-geo",
        "--geo-start-epoch",
        "1",
        "--geo-ramp-epochs",
        "6",
        "--geo-target-scale",
        "0.65",
        "--geo-end-scale",
        "0.45",
        "--geo-decay-start-epoch",
        "20",
        "--geo-low-rank-end-mult",
        "0.6",
        "--geo-low-rank-decay-start-epoch",
        "22",
        "--disable-strong-aug",
        "--lr",
        "3e-4",
        "--weight-decay",
        "0.08",
        "--label-smoothing",
        "0.05",
        "--ema-decay",
        "0",
        "--grad-clip-norm",
        "0.5",
    ],
    "smoke_mid192_geo_minlr001": [
        "--run-name",
        "modal_smoke_geovit_mid192d6_rank114_spec085_noclip_wd008_minlr001_e40",
        "--epochs",
        "40",
        "--limit-train",
        "2000",
        "--limit-test",
        "500",
        "--batch-size",
        "96",
        "--eval-batch-size",
        "192",
        "--embed-dim",
        "192",
        "--depth",
        "6",
        "--num-heads",
        "6",
        "--fc1-base-rank",
        "114",
        "--residual-scale",
        "0.85",
        "--spectral-scale",
        "0.85",
        "--low-rank-scale",
        "0.5",
        "--rotation-scale",
        "0.0",
        "--disable-local-geo",
        "--geo-start-epoch",
        "1",
        "--geo-ramp-epochs",
        "6",
        "--geo-target-scale",
        "0.65",
        "--geo-end-scale",
        "0.45",
        "--geo-decay-start-epoch",
        "20",
        "--geo-low-rank-end-mult",
        "0.6",
        "--geo-low-rank-decay-start-epoch",
        "22",
        "--disable-strong-aug",
        "--lr",
        "3e-4",
        "--weight-decay",
        "0.08",
        "--label-smoothing",
        "0.05",
        "--ema-decay",
        "0",
        "--min-lr-ratio",
        "0.01",
    ],
    # === Flow-Depth ViT presets (param-matched to plain ViT 2.93M) ===
    # FD-ViT: 480d/10heads, 1 shared block x12 iters = 2.89M params, eff depth 12
    "full_fdvit_480d_t12_e150": [
        "--run-name", "modal_full_fdvit_480d_t12",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "12",
        "--flow-depth-inject", "0.1",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "480", "--num-heads", "10",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # FD-ViT with Hamiltonian momentum: 480d x12
    "full_fdvit_480d_t12_mom_e150": [
        "--run-name", "modal_full_fdvit_480d_t12_mom",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "12",
        "--flow-depth-inject", "0.1",
        "--flow-depth-momentum",
        "--flow-depth-momentum-beta", "0.9",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "480", "--num-heads", "10",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # FD-ViT hybrid: 2 independent + 10 shared, 288d = 3.07M params
    "full_fdvit_288d_h2t12_e150": [
        "--run-name", "modal_full_fdvit_288d_h2t12",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "12",
        "--flow-depth-independent-blocks", "2",
        "--flow-depth-inject", "0.1",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "288", "--num-heads", "9",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # FD-ViT deep: 16 iterations, 480d
    "full_fdvit_480d_t16_e150": [
        "--run-name", "modal_full_fdvit_480d_t16",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "16",
        "--flow-depth-inject", "0.1",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "480", "--num-heads", "10",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # === High-resolution FD-ViT (patch_size=2 → 256 tokens) ===
    # FD-ViT 480d/T12/patch2/300ep: same params as winner but 4x spatial resolution
    "full_fdvit_480d_t12_p2_e300": [
        "--run-name", "modal_full_fdvit_480d_t12_p2_e300",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "12",
        "--flow-depth-inject", "0.1",
        "--flow-depth-time-conditioning",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "2",
        "--embed-dim", "480", "--num-heads", "10",
        "--drop-path-rate", "0.1",
        "--grad-clip-norm", "1.0",
        "--epochs", "300", "--warmup-epochs", "20",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.005",
        "--lr", "0.0008", "--weight-decay", "0.05",
        "--batch-size", "128", "--eval-batch-size", "256",
        "--ema-decay", "0.9999",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # FD-ViT 384d/T12/patch2/300ep: lighter with high resolution
    "full_fdvit_384d_t12_p2_e300": [
        "--run-name", "modal_full_fdvit_384d_t12_p2_e300",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "12",
        "--flow-depth-inject", "0.1",
        "--flow-depth-time-conditioning",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "2",
        "--embed-dim", "384", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--grad-clip-norm", "1.0",
        "--epochs", "300", "--warmup-epochs", "20",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.005",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "128", "--eval-batch-size", "256",
        "--ema-decay", "0.9999",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # FD-ViT 640d/T12/300ep — safe width, proven depth, lower LR: ~4.9M params
    "full_fdvit_640d_t12_e300": [
        "--run-name", "modal_full_fdvit_640d_t12_e300",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "12",
        "--flow-depth-inject", "0.1",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "640", "--num-heads", "10",
        "--drop-path-rate", "0.1",
        "--grad-clip-norm", "1.0",
        "--epochs", "300", "--warmup-epochs", "20",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.005",
        "--lr", "0.0008", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--ema-decay", "0.9999",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # FD-ViT 480d/T12/TC/300ep — add time conditioning to 76% winner
    "full_fdvit_480d_t12_tc_e300": [
        "--run-name", "modal_full_fdvit_480d_t12_tc_e300",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "12",
        "--flow-depth-inject", "0.1",
        "--flow-depth-time-conditioning",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "480", "--num-heads", "10",
        "--drop-path-rate", "0.1",
        "--grad-clip-norm", "1.0",
        "--epochs", "300", "--warmup-epochs", "20",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.005",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--ema-decay", "0.9999",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # === Scaled-up FD-ViT configs (FAILED - unstable at T16) ===
    # FD-ViT 640d/16iter/300ep + time conditioning + grad clip: ~5.1M params
    "full_fdvit_640d_t16_tc_e300": [
        "--run-name", "modal_full_fdvit_640d_t16_tc_e300",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "16",
        "--flow-depth-inject", "0.1",
        "--flow-depth-time-conditioning",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "640", "--num-heads", "10",
        "--drop-path-rate", "0.1",
        "--grad-clip-norm", "1.0",
        "--epochs", "300", "--warmup-epochs", "20",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.005",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--ema-decay", "0.9999",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # FD-ViT 480d/12iter/300ep — double training on proven 72.68% config
    "full_fdvit_480d_t12_e300": [
        "--run-name", "modal_full_fdvit_480d_t12_e300",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "12",
        "--flow-depth-inject", "0.1",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "480", "--num-heads", "10",
        "--drop-path-rate", "0.1",
        "--grad-clip-norm", "1.0",
        "--epochs", "300", "--warmup-epochs", "20",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.005",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--ema-decay", "0.9999",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # FD-ViT 640d/16iter/300ep + time + attn pool — full package
    "full_fdvit_640d_t16_full_e300": [
        "--run-name", "modal_full_fdvit_640d_t16_full_e300",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "16",
        "--flow-depth-inject", "0.1",
        "--flow-depth-time-conditioning",
        "--flow-depth-attn-pool",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "640", "--num-heads", "10",
        "--drop-path-rate", "0.1",
        "--grad-clip-norm", "1.0",
        "--epochs", "300", "--warmup-epochs", "20",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.005",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--ema-decay", "0.9999",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # FD-ViT 768d/16iter/300ep + time — ~7.2M params, pushes for 78%+
    "full_fdvit_768d_t16_tc_e300": [
        "--run-name", "modal_full_fdvit_768d_t16_tc_e300",
        "--seed", "0",
        "--flow-depth-mode",
        "--flow-depth-iterations", "16",
        "--flow-depth-inject", "0.1",
        "--flow-depth-time-conditioning",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "768", "--num-heads", "12",
        "--drop-path-rate", "0.15",
        "--grad-clip-norm", "1.0",
        "--epochs", "300", "--warmup-epochs", "20",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.005",
        "--lr", "0.0008", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--ema-decay", "0.9999",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    "full_med256d8_plain_e150": [
        "--run-name", "modal_full_med256d8_plain",
        "--seed", "0",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "256", "--depth", "8", "--num-heads", "8",
        "--drop-path-rate", "0.15",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    "full_med256d8_fnfl_e150": [
        "--run-name", "modal_full_med256d8_fnfl",
        "--seed", "0",
        "--no-geo-on-fc1",
        "--fnfl-last-k-blocks", "4",
        "--fnfl-num-steps", "4",
        "--fnfl-rank", "128",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "8",
        "--fnfl-strength-init", "0.0",
        "--fnfl-strength-anneal-epochs", "75",
        "--fnfl-strength-max", "1.0",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "256", "--depth", "8", "--num-heads", "8",
        "--drop-path-rate", "0.15",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # Full CIFAR-100 (50k/10k) — FNFL full-strength, matched recipe to full_plain_mid192d6_e150
    "full_fnfl_mid192d6_e150": [
        "--run-name", "modal_full_fnfl_mid192d6_e150",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
        "--fnfl-last-k-blocks", "2",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "64",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "4",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--fnfl-strength-max", "1.0",
    ],
    # FNFL with larger chart (rank=128) to reduce bottleneck at full scale.
    # Hypothesis: 64-dim chart limits capacity at 50k samples; rank=128 fixes it.
    "full_fnfl_r128_mid192d6_e150": [
        "--run-name", "modal_full_fnfl_r128_mid192d6_e150",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
        "--fnfl-last-k-blocks", "2",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "128",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "8",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--fnfl-strength-max", "1.0",
    ],
    # FNFL r128 with chart LayerNorm fix: prevents proj_out from absorbing h scale.
    # Previous run (full_fnfl_r128) showed h_norm collapsing from 1.23→0.04 over 150ep,
    # making the flow operator irrelevant. chart_norm is now baked into FlowFFN code.
    "full_fnfl_r128_cn_mid192d6_e150": [
        "--run-name", "modal_full_fnfl_r128_cn_mid192d6_e150",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
        "--fnfl-last-k-blocks", "2",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "128",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "8",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--fnfl-strength-max", "1.0",
    ],
    # FNFL k=6 (all blocks) at full scale with rank=128.
    "full_fnfl_r128_k6_mid192d6_e150": [
        "--run-name", "modal_full_fnfl_r128_k6_mid192d6_e150",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
        "--fnfl-last-k-blocks", "6",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "128",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "8",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--fnfl-strength-max", "1.0",
    ],
    "full_plain_mid192d6_e150": [
        "--run-name", "modal_full_plain_mid192d6_e150",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    "full_plain_s1": [
        "--run-name", "modal_full_plain_s1",
        "--seed", "1",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    "full_plain_s2": [
        "--run-name", "modal_full_plain_s2",
        "--seed", "2",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    # Full CIFAR-100 AGFF — all 6 blocks, 150 epochs, matched recipe
    "full_agff_k6_mid192d6_e150": [
        "--run-name", "modal_full_agff_k6_s0",
        "--seed", "0",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
        "--agff-last-k-blocks", "6",
    ],
    "full_fnfl_k4_t2_mid192d6_e150": [
        "--run-name", "modal_full_fnfl_k4t2_s0",
        "--seed", "0",
        "--no-geo-on-fc1",
        "--fnfl-last-k-blocks", "4",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "64",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    "full_fnfl_k4_t2_s1": [
        "--run-name", "modal_full_fnfl_k4t2_s1",
        "--seed", "1",
        "--no-geo-on-fc1",
        "--fnfl-last-k-blocks", "4",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "64",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    "full_fnfl_k4_t2_s2": [
        "--run-name", "modal_full_fnfl_k4t2_s2",
        "--seed", "2",
        "--no-geo-on-fc1",
        "--fnfl-last-k-blocks", "4",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "64",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
    ],
    "smoke_plain_locked_mid192d6_e40": [
        "--run-name",
        "modal_smoke_plain_locked_mid192d6_e40",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--no-geo-on-fc1",
    ],
    # AGFF (Attention-Gated FFN): all 6 blocks, three seeds for significance
    "smoke_agff_k6_locked_mid192d6_e40": [
        "--run-name",
        "modal_smoke_agff_k6_locked_s0",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks",
        "6",
        "--seed",
        "0",
    ],
    "smoke_agff_k6_locked_mid192d6_e40_s1": [
        "--run-name",
        "modal_smoke_agff_k6_locked_s1",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks",
        "6",
        "--seed",
        "1",
    ],
    "smoke_agff_k6_locked_mid192d6_e40_s2": [
        "--run-name",
        "modal_smoke_agff_k6_locked_s2",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks",
        "6",
        "--seed",
        "2",
    ],
    # AGFF v2: gate_ln=True + Xavier gate init (fixes gate collapse)
    # Mode 'attn': pure cross-token gate
    "smoke_agff_k6_v2_s0_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_v2_s0",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "attn",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "0",
    ],
    "smoke_agff_k6_v2_s1_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_v2_s1",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "attn",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "1",
    ],
    "smoke_agff_k6_v2_s2_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_v2_s2",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "attn",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "2",
    ],
    # Mode 'dual': gate = sigmoid(W@LN(attn) + V@x) — anchored to token
    "smoke_agff_k6_dual_s0_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_dual_s0",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "dual",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "0",
    ],
    "smoke_agff_k6_dual_s1_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_dual_s1",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "dual",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "1",
    ],
    "smoke_agff_k6_dual_s2_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_dual_s2",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "dual",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "2",
    ],
    # Mode 'scale': gate = 1 + tanh(W@LN(attn)) — multiplicative, range [0,2]
    "smoke_agff_k6_scale_s0_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_scale_s0",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "scale",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "0",
    ],
    "smoke_agff_k6_scale_s1_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_scale_s1",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "scale",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "1",
    ],
    "smoke_agff_k6_scale_s2_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_scale_s2",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "scale",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "2",
    ],
    # k=2 (late-tail only): fewer gated blocks → less gate noise at smoke scale
    "smoke_agff_k2_v2_s0_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k2_v2_s0",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "2",
        "--agff-gate-mode", "attn",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "0",
    ],
    "smoke_agff_k2_v2_s1_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k2_v2_s1",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "2",
        "--agff-gate-mode", "attn",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "1",
    ],
    "smoke_agff_k2_v2_s2_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k2_v2_s2",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "2",
        "--agff-gate-mode", "attn",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "2",
    ],
    # k=6 with tiny gate init (std=0.005): gate barely active, just enough to regularize
    "smoke_agff_k6_tiny_s0_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_tiny_s0",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "attn",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "0.005",
        "--seed", "0",
    ],
    "smoke_agff_k6_tiny_s1_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_tiny_s1",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "attn",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "0.005",
        "--seed", "1",
    ],
    "smoke_agff_k6_tiny_s2_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_tiny_s2",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "attn",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "0.005",
        "--seed", "2",
    ],
    # k=6 with CLS-only gate: use only CLS token as global context signal (more stable)
    "smoke_agff_k6_cls_s0_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_cls_s0",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "cls",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "0",
    ],
    "smoke_agff_k6_cls_s1_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_cls_s1",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "cls",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "1",
    ],
    "smoke_agff_k6_cls_s2_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_agff_k6_cls_s2",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--agff-last-k-blocks", "6",
        "--agff-gate-mode", "cls",
        "--agff-gate-ln",
        "--agff-gate-init-scale", "-1.0",
        "--seed", "2",
    ],
    "smoke_fnfl_k2_t2_locked_mid192d6_e40": [
        "--run-name",
        "modal_smoke_fnfl_k2_t2_locked_mid192d6_e40",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--no-geo-on-fc1",
        "--fnfl-last-k-blocks",
        "2",
        "--fnfl-num-steps",
        "2",
        "--fnfl-rank",
        "64",
        "--fnfl-num-spectral-bases",
        "8",
        "--fnfl-low-rank",
        "4",
        "--fnfl-strength-init",
        "0.0",
        "--fnfl-strength-anneal-epochs",
        "20",
        "--fnfl-strength-max",
        "1.0",
    ],
    "smoke_fnfl_k2_t4_locked_mid192d6_e40": [
        "--run-name",
        "modal_smoke_fnfl_k2_t4_locked_mid192d6_e40",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--no-geo-on-fc1",
        "--fnfl-last-k-blocks",
        "2",
        "--fnfl-num-steps",
        "4",
        "--fnfl-rank",
        "64",
        "--fnfl-num-spectral-bases",
        "8",
        "--fnfl-low-rank",
        "4",
        "--fnfl-strength-init",
        "0.0",
        "--fnfl-strength-anneal-epochs",
        "20",
        "--fnfl-strength-max",
        "1.0",
    ],
    "smoke_fnfl_k2_t2_noskip_locked_mid192d6_e40": [
        "--run-name",
        "modal_smoke_fnfl_k2_t2_noskip_locked_mid192d6_e40",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--no-geo-on-fc1",
        "--fnfl-last-k-blocks",
        "2",
        "--fnfl-num-steps",
        "2",
        "--fnfl-rank",
        "64",
        "--fnfl-num-spectral-bases",
        "8",
        "--fnfl-low-rank",
        "4",
        "--fnfl-strength-init",
        "1.0",
        "--fnfl-strength-anneal-epochs",
        "0",
        "--fnfl-strength-max",
        "1.0",
    ],
    # Weight-tied FD-ViT on the locked smoke ladder. T=6 iterations of one
    # shared block matches the depth-6 effective depth of the other smokes.
    "smoke_fdvit_T6_locked_mid192d6_e40": [
        "--run-name",
        "modal_smoke_fdvit_T6_locked_mid192d6_e40",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--no-geo-on-fc1",
        "--flow-depth-mode",
        "--flow-depth-iterations",
        "6",
        "--flow-depth-inject",
        "0.1",
        "--flow-depth-time-conditioning",
    ],
    "smoke_geovit_simple_locked_mid192d6_e40": [
        "--run-name",
        "modal_smoke_geovit_simple_locked_mid192d6_e40",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--fc1-base-rank",
        "114",
        "--residual-scale",
        "0.85",
        "--spectral-scale",
        "0.85",
        "--low-rank-scale",
        "0.5",
        "--rotation-scale",
        "0.0",
        "--disable-local-geo",
        "--geo-start-epoch",
        "1",
        "--geo-ramp-epochs",
        "6",
        "--geo-target-scale",
        "0.65",
        "--geo-end-scale",
        "0.45",
        "--geo-decay-start-epoch",
        "20",
        "--geo-low-rank-end-mult",
        "0.6",
        "--geo-low-rank-decay-start-epoch",
        "22",
    ],
    "smoke_geovit_diffuse_locked_mid192d6_e40": [
        "--run-name",
        "modal_smoke_geovit_diffuse_locked_mid192d6_e40",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--fc1-base-rank",
        "114",
        "--residual-scale",
        "0.85",
        "--spectral-scale",
        "0.85",
        "--low-rank-scale",
        "0.5",
        "--rotation-scale",
        "0.0",
        "--disable-local-geo",
        "--geo-start-epoch",
        "1",
        "--geo-ramp-epochs",
        "6",
        "--geo-target-scale",
        "0.65",
        "--geo-end-scale",
        "0.45",
        "--geo-decay-start-epoch",
        "20",
        "--geo-low-rank-end-mult",
        "0.6",
        "--geo-low-rank-decay-start-epoch",
        "22",
        "--hidden-diffusion",
        "--hidden-diffusion-last-k-blocks",
        "2",
        "--hidden-diffusion-scale",
        "0.15",
    ],
    "smoke_geovit_magnus_single_locked_mid192d6_e40": [
        "--run-name",
        "modal_smoke_geovit_magnus_single_locked_mid192d6_e40",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--fc1-base-rank",
        "114",
        "--residual-scale",
        "0.85",
        "--disable-local-geo",
        "--rotation-scale",
        "0.0",
        "--geo-start-epoch",
        "1",
        "--geo-ramp-epochs",
        "6",
        "--geo-target-scale",
        "0.65",
        "--geo-end-scale",
        "0.45",
        "--geo-decay-start-epoch",
        "20",
        "--magnus-single-operator",
        "--flow-rank",
        "4",
        "--no-share-fc1-bank",
        "--no-share-fc1-conditioner",
    ],
    "smoke_geovit_coupled_learnable_locked_mid192d6_e40": [
        "--run-name",
        "modal_smoke_geovit_coupled_learnable_locked_mid192d6_e40",
        "--locked-smoke-protocol",
        "mid192d6_e40",
        "--fc1-base-rank",
        "108",
        "--residual-scale",
        "0.85",
        "--geo-residual-budget",
        "0.125",
        "--spectral-scale",
        "0.75",
        "--low-rank-scale",
        "0.5",
        "--rotation-scale",
        "0.0",
        "--disable-local-geo",
        "--geo-start-epoch",
        "1",
        "--geo-ramp-epochs",
        "6",
        "--geo-target-scale",
        "0.65",
        "--geo-end-scale",
        "0.35",
        "--geo-decay-start-epoch",
        "18",
        "--geo-low-rank-end-mult",
        "0.5",
        "--geo-low-rank-decay-start-epoch",
        "20",
        "--coupled-spectral-low-rank",
        "--coupled-learnable-input-basis",
    ],
    # --- GradFlow FFN presets (conservative gate: sigmoid(-4)≈0.018 at init) ---
    # GFN k=2: correction branch on last 2 blocks.
    "smoke_gfn_k2_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_gfn_k2_locked_mid192d6_e40",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--gfn-last-k-blocks", "2",
        "--gfn-corr-bottleneck", "32",
        "--gfn-n-train-iters", "1",
        "--gfn-gate-init", "-4.0",
    ],
    # GFN k=6: correction branch on all 6 blocks.
    "smoke_gfn_k6_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_gfn_k6_locked_mid192d6_e40",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--gfn-last-k-blocks", "6",
        "--gfn-corr-bottleneck", "32",
        "--gfn-n-train-iters", "1",
        "--gfn-gate-init", "-4.0",
    ],
    # GFN k=6 with 2 correction iterations at train time.
    "smoke_gfn_k6_iter2_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_gfn_k6_iter2_locked_mid192d6_e40",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--gfn-last-k-blocks", "6",
        "--gfn-corr-bottleneck", "32",
        "--gfn-n-train-iters", "2",
        "--gfn-gate-init", "-4.0",
    ],
    # Fixed FNFL: full strength from epoch 0 (bypasses the anneal bug).
    "smoke_fnfl_k2_full_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_fnfl_k2_full_locked_mid192d6_e40",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--fnfl-last-k-blocks", "2",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "64",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "4",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--fnfl-strength-max", "1.0",
    ],
    # --- Multi-seed validation seeds ---
    "smoke_plain_s1_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_plain_s1_locked_mid192d6_e40",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--seed", "1",
    ],
    "smoke_plain_s2_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_plain_s2_locked_mid192d6_e40",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--seed", "2",
    ],
    "smoke_fnfl_full_s1_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_fnfl_full_s1_locked_mid192d6_e40",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--fnfl-last-k-blocks", "2",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "64",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "4",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--fnfl-strength-max", "1.0",
        "--seed", "1",
    ],
    "smoke_fnfl_full_s2_locked_mid192d6_e40": [
        "--run-name", "modal_smoke_fnfl_full_s2_locked_mid192d6_e40",
        "--locked-smoke-protocol", "mid192d6_e40",
        "--no-geo-on-fc1",
        "--fnfl-last-k-blocks", "2",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "64",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "4",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--fnfl-strength-max", "1.0",
        "--seed", "2",
    ],
    # --- Medium scale (10k/2k) — standalone presets, NO locked protocol ---
    # All hyperparams copied from mid192d6_e40 but with 10k train / 2k test and
    # 60 epochs. Do NOT use --locked-smoke-protocol here or it will override
    # limit_train back to 2000.
    "med_fnfl_full_10k_mid192d6_e60": [
        "--run-name", "modal_med_fnfl_full_10k_mid192d6_e60",
        "--no-geo-on-fc1",
        "--img-size", "32",
        "--patch-size", "4",
        "--embed-dim", "192",
        "--depth", "6",
        "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--limit-train", "10000",
        "--limit-test", "2000",
        "--epochs", "60",
        "--batch-size", "128",
        "--eval-batch-size", "256",
        "--num-workers", "4",
        "--lr", "3e-4",
        "--warmup-epochs", "5",
        "--min-lr-ratio", "0.05",
        "--weight-decay", "0.05",
        "--label-smoothing", "0.05",
        "--disable-strong-aug",
        "--fnfl-last-k-blocks", "2",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "64",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "4",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--fnfl-strength-max", "1.0",
    ],
    # FNFL r128 with chart_norm + Xavier-init fix at medium scale.
    # Previous full-scale run: step_gate collapsed 0.5→0.13 (flow dead), best=69.66%.
    # Root cause: spectral_basis std=0.02 → delta≈0.002×h_norm → gate drives to 0 instead.
    # Fix: std=1/sqrt(chart_dim)≈0.088 so delta≈0.1×h_norm from epoch 1.
    "med_fnfl_r128_cn_xi_10k_mid192d6_e60": [
        "--run-name", "modal_med_fnfl_r128_cn_xi_10k_mid192d6_e60",
        "--no-geo-on-fc1",
        "--img-size", "32",
        "--patch-size", "4",
        "--embed-dim", "192",
        "--depth", "6",
        "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--limit-train", "10000",
        "--limit-test", "2000",
        "--epochs", "60",
        "--batch-size", "128",
        "--eval-batch-size", "256",
        "--num-workers", "4",
        "--lr", "3e-4",
        "--warmup-epochs", "5",
        "--min-lr-ratio", "0.05",
        "--weight-decay", "0.05",
        "--label-smoothing", "0.05",
        "--disable-strong-aug",
        "--fnfl-last-k-blocks", "2",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "128",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "8",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--fnfl-strength-max", "1.0",
    ],
    # Full-scale FNFL r128 with chart_norm + Xavier-init fix.
    "full_fnfl_r128_cn_xi_mid192d6_e150": [
        "--run-name", "modal_full_fnfl_r128_cn_xi_mid192d6_e150",
        "--no-geo-on-fc1",
        "--img-size", "32", "--patch-size", "4",
        "--embed-dim", "192", "--depth", "6", "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--epochs", "150", "--warmup-epochs", "10",
        "--warmup-start-factor", "0.1", "--min-lr-ratio", "0.01",
        "--lr", "0.001", "--weight-decay", "0.05",
        "--batch-size", "256", "--eval-batch-size", "512",
        "--mixup-alpha", "0.8", "--cutmix-alpha", "1.0",
        "--mix-prob", "1.0", "--cutmix-switch-prob", "0.5",
        "--label-smoothing", "0.1",
        "--num-workers", "4",
        "--fnfl-last-k-blocks", "2",
        "--fnfl-num-steps", "2",
        "--fnfl-rank", "128",
        "--fnfl-num-spectral-bases", "8",
        "--fnfl-low-rank", "8",
        "--fnfl-strength-init", "1.0",
        "--fnfl-strength-anneal-epochs", "0",
        "--fnfl-strength-max", "1.0",
    ],
    "med_plain_10k_mid192d6_e60": [
        "--run-name", "modal_med_plain_10k_mid192d6_e60",
        "--no-geo-on-fc1",
        "--img-size", "32",
        "--patch-size", "4",
        "--embed-dim", "192",
        "--depth", "6",
        "--num-heads", "6",
        "--drop-path-rate", "0.1",
        "--limit-train", "10000",
        "--limit-test", "2000",
        "--epochs", "60",
        "--batch-size", "128",
        "--eval-batch-size", "256",
        "--num-workers", "4",
        "--lr", "3e-4",
        "--warmup-epochs", "5",
        "--min-lr-ratio", "0.05",
        "--weight-decay", "0.05",
        "--label-smoothing", "0.05",
        "--disable-strong-aug",
    ],
}


def get_preset_args(name: str) -> list[str]:
    key = str(name).strip()
    if not key:
        return []
    if key not in PRESET_ARGS:
        known = ", ".join(sorted(PRESET_ARGS))
        raise KeyError(f"Unknown GeoViT preset '{key}'. Known presets: {known}")
    return list(PRESET_ARGS[key])


def list_presets() -> list[str]:
    return sorted(PRESET_ARGS)
